---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src
  label: Pages
  create: documents
  match: "*.md"
  exclude: "*.json, feed.md"
  new_doc_ext: md
- type: directory
  path: src/journal
  label: Journal
  create: documents
  match: "**/*.md"
  exclude: "*.json"
  new_doc_ext: md
- type: directory
  path: src/portfolio
  label: Portfolio
  create: documents
  match: "**/*.md"
  exclude: "*.json"
  new_doc_ext: md
upload_dir: src/images/uploads
public_path: "/images/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: build
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
