---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src
  label: Content
  create: all
  match: "**/*.md"
  new_doc_ext: ".md"
- type: directory
  path: src/portfolio
  label: Portfolio
  create: documents
  match: "**/*"
  exclude: "*.json"
  new_doc_ext: md
- type: directory
  path: src/journal
  label: Journal
  create: documents
  match: "**/*"
  exclude: "*.json"
  new_doc_ext: md
upload_dir: src/images/uploads
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: "/build"
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm start
