backend:
  name: git-gateway
  branch: master
  repo: sts24/sts-eleventy
publish_mode: editorial_workflow
media_folder: "src/images/uploads"
public_folder: "/images/uploads"
site_url: "https://scottsmith.netlify.com"
show_preview_links: true
collections: 
  - name: "journal"
    label: "Journal"
    folder: "src/journal"
    slug: "{{slug}}"
    preview_path: "journal/{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true, required: false}
      - {label: "URL", name: "url", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    folder: "src/"
    slug: "{{slug}}"
    preview_path: "/{{slug}}"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/page.njk" }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/portfolio"
    slug: "{{slug}}"
    preview_path: "portfolio/{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true, required: false}
      - {label: "Tools", name: "tools", widget: "list", allow_add: true, required: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false }
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Showcase"
        name: "showcase"
        widget: "list"
        fields:
          - { label: "Showcase Item", name: "showcaseItem", widget: "image" }
          - { label: "Description", name: "description", widget: "markdown" }
  - name: "settings"
    label: "⚙ Settings"
    files:
      - label: "Site"
        name: "site"
        delete: false
        file: "src/_data/settings.json"
        fields:
          - {label: "Site Name", name: "siteName", widget: "string"}
          - {label: "Maximum Posts Per Page", name: "maxPostsPerPage", widget: "number" }
          - {label: "Profile Image", name: "profileImage", widget: "image", allow_multiple: false }
          - {label: "Intro Copy", name: "introCopy", widget: "text"}
      - label: "Navigation"
        name: "navigation"
        delete: false
        file: "src/_data/navigation.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "text", widget: "string"}
              - { label: "URL", name: "url", widget: "string"}
      - label: "Social Media Links"
        name: "social_media"
        delete: false
        file: "src/_data/social_media.json"
        fields:
          - label: "Links"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string"}
              - { label: "URL", name: "url", widget: "string"}
              - { label: "Icon", name: "icon", widget: "string"}