backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "src/images/uploads"
collections: 
  - name: "journal"
    label: "Journal"
    folder: "src/journal"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true, required: false}
      - {label: "URL", name: "url", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    folder: "src/"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/portfolio"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true, required: false}
      - {label: "Tools", name: "tools", widget: "list", allow_add: true, required: false}
      - {label: "Image", name: "image", widget: "image", required: false }
      - {label: "Body", name: "body", widget: "markdown"}