backend:
  name: git-gateway
  branch: 2020-summer
publish_mode: editorial_workflow
media_folder: "images/uploads"
collections:
  - name: "journal"
    label: "Journal Post"
    folder: "journal/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "url", widget: "string"}